const userActionTypes = {
    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    ADD_CURRENT_USER: 'ADD_CURRENT_USER',
    CHANGE_CURRENT_USER: 'CHANGE_CURRENT_USER',
    GET_USERS: 'GET_USERS',
    GET_USER_BY_ID: 'GET_USER_BY_ID',
    LOADING_FETCHING: 'LOADING_FETCHING',
    GET_POST_BY_ID: 'GET_POST_BY_ID',
    GET_FEED: 'GET_FEED',
    GET_COMMENTS_BY_POST_ID: 'GET_COMMENTS_BY_POST_ID'
  }

  export default userActionTypes;